-- ============================================
-- GAMSTART DATABASE SCHEMA
-- Run this in your Supabase SQL Editor
-- ============================================

-- 1. KNOWN PROXIES TABLE
-- Casino deposit addresses (B in the A → B → C flow)
-- Populated by indexing casino hot wallets
CREATE TABLE IF NOT EXISTS known_proxies (
  address TEXT PRIMARY KEY,
  casino_name TEXT NOT NULL,
  first_seen TIMESTAMPTZ DEFAULT NOW(),
  last_seen TIMESTAMPTZ DEFAULT NOW()
);

-- Index for casino name lookups
CREATE INDEX IF NOT EXISTS idx_known_proxies_casino ON known_proxies(casino_name);


-- 2. WALLET LINKS TABLE
-- Maps personal wallets (A) to their casino deposit proxies (B)
-- Populated on-demand when a user scans their wallet
CREATE TABLE IF NOT EXISTS wallet_links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  personal_wallet TEXT NOT NULL,
  proxy_address TEXT NOT NULL,
  casino_name TEXT,
  first_seen TIMESTAMPTZ DEFAULT NOW(),
  tx_count INTEGER DEFAULT 0,
  total_value_eth NUMERIC DEFAULT 0,
  UNIQUE(personal_wallet, proxy_address)
);

-- Indexes for fast lookups
CREATE INDEX IF NOT EXISTS idx_wallet_links_personal ON wallet_links(personal_wallet);
CREATE INDEX IF NOT EXISTS idx_wallet_links_proxy ON wallet_links(proxy_address);


-- 3. TRANSACTIONS TABLE
-- Individual gambling transactions
-- Populated when scanning user wallets
CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tx_hash TEXT UNIQUE NOT NULL,
  from_address TEXT NOT NULL,
  to_address TEXT NOT NULL,
  casino_name TEXT,
  value_eth NUMERIC DEFAULT 0,
  value_usd NUMERIC DEFAULT 0,
  asset TEXT DEFAULT 'ETH',
  chain TEXT DEFAULT 'ETH',
  block_number BIGINT,
  block_timestamp TIMESTAMPTZ NOT NULL
);

-- Indexes for efficient querying
CREATE INDEX IF NOT EXISTS idx_transactions_from ON transactions(from_address);
CREATE INDEX IF NOT EXISTS idx_transactions_to ON transactions(to_address);
CREATE INDEX IF NOT EXISTS idx_transactions_casino ON transactions(casino_name);
CREATE INDEX IF NOT EXISTS idx_transactions_timestamp ON transactions(block_timestamp);


-- 4. WALLETS TABLE
-- Cached wallet reports (the diagnostic results)
-- Updated after each scan, serves as cache for repeat scans
CREATE TABLE IF NOT EXISTS wallets (
  address TEXT PRIMARY KEY,
  chain TEXT DEFAULT 'ETH',
  risk_score INTEGER,
  status TEXT,
  gambler_type TEXT,
  total_deposits INTEGER DEFAULT 0,
  total_volume_usd NUMERIC DEFAULT 0,
  total_volume_eth NUMERIC DEFAULT 0,
  favorite_casino TEXT,
  first_deposit DATE,
  last_deposit DATE,
  active_days INTEGER DEFAULT 0,
  deposit_velocity NUMERIC,
  midnight_factor NUMERIC,
  chase_behavior NUMERIC,
  avg_session_hours NUMERIC,
  biggest_deposit_eth NUMERIC,
  biggest_deposit_usd NUMERIC,
  longest_streak INTEGER,
  data JSONB, -- Full analytics data (monthly deposits, breakdowns, etc.)
  last_scanned TIMESTAMPTZ DEFAULT NOW(),
  scan_count INTEGER DEFAULT 1
);

-- Index for status lookups (for leaderboard)
CREATE INDEX IF NOT EXISTS idx_wallets_risk ON wallets(risk_score DESC);
CREATE INDEX IF NOT EXISTS idx_wallets_status ON wallets(status);
CREATE INDEX IF NOT EXISTS idx_wallets_volume ON wallets(total_volume_usd DESC);


-- 5. PLATFORM SNAPSHOTS TABLE
-- Daily snapshots of casino analytics
-- Populated by a scheduled job
CREATE TABLE IF NOT EXISTS platform_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  snapshot_date DATE NOT NULL,
  casino_name TEXT NOT NULL,
  total_volume NUMERIC DEFAULT 0,
  total_deposits BIGINT DEFAULT 0,
  new_depositors BIGINT DEFAULT 0,
  unique_depositors BIGINT DEFAULT 0,
  avg_deposit_size NUMERIC DEFAULT 0,
  market_share NUMERIC DEFAULT 0,
  UNIQUE(snapshot_date, casino_name)
);

-- Index for date-based queries
CREATE INDEX IF NOT EXISTS idx_platform_snapshots_date ON platform_snapshots(snapshot_date DESC);
CREATE INDEX IF NOT EXISTS idx_platform_snapshots_casino ON platform_snapshots(casino_name);


-- ============================================
-- OPTIONAL: ROW LEVEL SECURITY (RLS)
-- Enable if you want to restrict access
-- ============================================

-- Disable RLS for now (enable later for production)
ALTER TABLE known_proxies DISABLE ROW LEVEL SECURITY;
ALTER TABLE wallet_links DISABLE ROW LEVEL SECURITY;
ALTER TABLE transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE wallets DISABLE ROW LEVEL SECURITY;
ALTER TABLE platform_snapshots DISABLE ROW LEVEL SECURITY;


-- ============================================
-- SAMPLE DATA FOR TESTING
-- Uncomment and run to test with sample data
-- ============================================

/*
-- Sample known proxies (casino deposit addresses)
INSERT INTO known_proxies (address, casino_name) VALUES
  ('0x68416debc20d13e5ef694cdcac9506f4c1a20184', '500 Casino'),
  ('0x014435b1e39945cf4f5f0c3cbb5833195a95cc9b', 'Duelbits'),
  ('0x580450dff316ae00d0fbef9621a304020a046ce2', 'Gamdom'),
  ('0x7b09fc3bdd9a1eb0059f0c9d391f5d684e0f9918', 'Duel'),
  ('0xcbd6832ebc203e49e2b771897067fce3c58575ac', 'Rollbit'),
  ('0xc94ebb328ac25b95db0e0aa968371885fa516215', 'Roobet'),
  ('0xa26148ae51fa8e787df319c04137602cc018b521', 'Roobet')
ON CONFLICT (address) DO NOTHING;
*/
